export enum API_OPERATIONS {
  FETCH_USER = 'FETCH_USER',
  FETCH_USER_MEETING = 'FETCH_USER_MEETING',
  FETCH_SIGNED_URL = 'FETCH_SIGNED_URL',
  UPLOAD_RECORDING = 'UPLOAD_RECORDING',
  UPLOAD_RECORDING_OPERATION = 'UPLOAD_RECORDING_OPERATION',
  PROCESS_RECORDING = 'PROCESS_RECORDING',
}
