export enum UI_COMPONENT_DATA_TEST_ID {
  ERROR_COMPONENT = 'ERROR_COMPONENT',
  SPINNER_COMPONENT = 'SPINNER_COMPONENT',

  MEETING_COMPONENT = 'MEETING_COMPONENT',
  ACTIVE_MEETING_COMPONENT = 'ACTIVE_MEETING_COMPONENT',
  UPCOMING_MEETING_COMPONENT = 'UPCOMING_MEETING_COMPONENT',
  PAST_MEETING_COMPONENT = 'PAST_MEETING_COMPONENT',

  ALL_DONE_FOR_TODAY = 'ALL_DONE_FOR_TODAY',
  NO_MEETING_FOR_THE_DAY = 'NO_MEETING_FOR_THE_DAY',

  CONNECTED_TO_USER = 'CONNECTED_TO_USER',

  SETTING_ICON = 'SETTING_ICON',
  HOME_ICON = 'HOME_ICON',
  REFETCH_ICON = 'REFETCH_ICON',

  API_INPUT_TAG = 'API_INPUT_TAG',
}

export enum PATHS {
  SETUP_PAGE = '/setup',
  HOME_PAGE = '/',
}
